// Predefined roles for management team members
export const predefinedRoles = [
  { value: 1, name: "President" },
  { value: 2, name: "Vice President" },
  { value: 3, name: "General Secretary" },
  { value: 4, name: "Executive Officer" },
  { value: 5, name: "Deputy General Secretary" },
  { value: 6, name: "Executive Administrator" },
  { value: 7, name: "Finance Manager" },
  { value: 8, name: "Assistant Finance Manager" },
  { value: 9, name: "Technical Head" },
  { value: 10, name: "Assistant Technical Head" },
  { value: 11, name: "Cultural Editor" },
  { value: 12, name: "Cultural Editor (Female)" },
  { value: 13, name: "Assistant Cultural Editor" },
  { value: 14, name: "Publicity Secretary" },
  { value: 15, name: "Associate Publicity Secretary" },
];

// Mock data for management team
export const managementTeam = [
  {
    id: 1,
    name: "Alex Johnson",
    roleId: 1, // President
    gender: "Male",
    department: "Computer Science",
    session: "2021-2025",
    roll: "R-2001",
    semester: 6,
    shift: "Morning",
    skills: [
      "Leadership",
      "Public Speaking",
      "Strategic Planning",
      "Team Building",
      "Decision Making",
      "Problem Solving",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2025-01-15",
    endTime: "2026-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=AJ",
  },
  {
    id: 2,
    name: "Sarah Williams",
    roleId: 2, // Vice President
    gender: "Female",
    department: "Business Administration",
    session: "2021-2025",
    roll: "R-2045",
    semester: 6,
    shift: "Day",
    skills: ["Team Management", "Event Planning", "Finance", "Communication"],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=SW",
  },
  {
    id: 3,
    name: "Michael Chen",
    roleId: 3, // General Secretary
    gender: "Male",
    department: "Electrical Engineering",
    session: "2022-2026",
    roll: "R-2189",
    semester: 4,
    shift: "Morning",
    skills: [
      "Documentation",
      "Communication",
      "Organization",
      "Time Management",
      "Meeting Coordination",
      "Record Keeping",
      "Email Management",
      "Report Writing",
      "Scheduling",
      "Administrative Support",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=MC",
  },
  {
    id: 4,
    name: "Emily Rodriguez",
    roleId: 7, // Finance Manager
    gender: "Female",
    department: "Business Administration",
    session: "2020-2024",
    roll: "R-1876",
    semester: 8,
    shift: "Day",
    skills: [
      "Accounting",
      "Budgeting",
      "Financial Analysis",
      "Expense Tracking",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=ER",
  },
  {
    id: 5,
    name: "David Kim",
    roleId: 9, // Technical Head
    gender: "Male",
    department: "Civil Engineering",
    session: "2022-2026",
    roll: "R-2256",
    semester: 4,
    shift: "Morning",
    skills: [
      "Web Development",
      "System Architecture",
      "UI/UX Design",
      "Database Management",
      "Cloud Computing",
      "Mobile App Development",
      "API Integration",
      "DevOps",
      "Version Control",
      "Agile Methodologies",
      "Technical Documentation",
      "Problem Solving",
      "Code Review",
      "Testing",
      "Debugging",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=DK",
  },
  {
    id: 6,
    name: "Jessica Lee",
    roleId: 11, // Cultural Editor
    gender: "Female",
    department: "Fine Arts",
    session: "2022-2026",
    roll: "R-2312",
    semester: 4,
    shift: "Day",
    skills: ["Content Creation", "Event Planning", "Creative Writing"],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=JL",
  },
  {
    id: 7,
    name: "Sophia Martinez",
    roleId: 12, // Cultural Editor (Female)
    gender: "Female",
    department: "Literature",
    session: "2021-2025",
    roll: "R-2145",
    semester: 6,
    shift: "Morning",
    skills: [
      "Editing",
      "Content Strategy",
      "Social Media",
      "Photography",
      "Graphic Design",
      "Event Management",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=SM",
  },
  {
    id: 8,
    name: "James Wilson",
    roleId: 14, // Publicity Secretary
    gender: "Male",
    department: "Marketing",
    session: "2020-2024",
    roll: "R-1923",
    semester: 8,
    shift: "Day",
    skills: [
      "Public Relations",
      "Marketing",
      "Social Media Management",
      "Content Creation",
      "Graphic Design",
      "Event Promotion",
      "Brand Management",
      "Communication Strategy",
      "Media Relations",
      "Campaign Planning",
      "Analytics",
      "Copywriting",
    ],
    electionName: "Annual Student Body Election 2023",
    startTime: "2023-01-15",
    endTime: "2024-01-14",
    avatar: "/placeholder.svg?height=100&width=100&text=JW",
  },
];
